### ISSUE TITLE
Python 3.10 compatibility

### ISSUE THREAD

**Issue by covogel** [tuwien-cms/xprec#14]
Hi, 

there seems to be a issue with xprec's compatibility :)

```
UnsatisfiableError: The following specifications were found to be incompatible 
with the existing python installation in your environment: 
Specifications:
- xprec -> python[version='>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0'] 
- Your python: python=3.10  
```
Thank you so much!

All the Best
Constanze

**Comment by shinaoka** [comment]
Thank you for the report. Do you use Python 3.10 with Anaconda?
I tried but it is not easy to provide a conda package for Python 3.10 at this point, due to the following issue.
We may have to wait for the next Anaconda release.

https://stackoverflow.com/questions/69523878/can-i-update-to-python-3-9-or-3-10-in-anaconda-base-root

**Comment by covogel** [comment]
Yes, I do!
All right, I will figure something out until then :)
Thank you nevertheless.

**Comment by shinaoka** [comment]
You could build & install `xprec` using `pip`, though I have never tried.

**Comment by shinaoka** [comment]
Now, we provide packages of `xprec` for Python 3.10.

**Comment by mwallerb** [comment]
Perfect, let's close this then
